x-dns: &custom_dns
  - "84.21.189.133"
  - "193.23.209.189"
  - "2a12:bec4:1460:294::2"
  - "2a01:ecc0:680:120::2"

services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:latest
    container_name: cli-proxy-api
    restart: unless-stopped
    networks:
      web:
        ipv4_address: 10.0.1.13
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./auth:/root/.cli-proxy-api
    dns: *custom_dns

  codex-auth-refresher:
    image: ghcr.io/pymba86/codex-auth-refresher:latest
    container_name: codex-auth-refresher
    pull_policy: always
    restart: unless-stopped
    networks:
      web:
        ipv4_address: 10.0.1.14
    environment:
      CODEX_AUTH_DIR: /data/auth
      CODEX_REFRESH_BEFORE: 6h
      CODEX_REFRESH_MAX_AGE: 6h
      CODEX_SCAN_INTERVAL: 5m
      CODEX_MAX_PARALLEL: 1
      CODEX_HTTP_TIMEOUT: 30s
      CODEX_LOG_FORMAT: json
      CODEX_STATUS_ENABLE: "true"
      CODEX_WEB_ENABLE: "true"
    volumes:
      - ./auth:/data/auth
    dns: *custom_dns

networks:
  web:
    external: true
